### ISSUE TITLE
Redesign Stop Arrival Times

### ISSUE THREAD

**Issue by luqmaan** [luqmaan/Instabus#151]
Especially with the fixed width on mobile

**Comment by itsjustluck** [comment]
Hi, my friend was telling me about your project, and I'm interested in helping. I do design and front-end development. I think I could help with this one.

**Comment by kanishka-azimi** [comment]
Total left field, but I think about bus stops and buses a lot...

This seems fine for most bus stops.

Generally, there are three modes when I am looking at bus times. 

1) Daily use, know the bus (I know the exact route number and time, just let me know if it is late and how late. If it is not late, don't show me anything)
2) Less frequent use, remembering schedules, exploring bus stops/buses available (I don't know the exact time of the bus. I may not even know which bus stops are active during what times of day or in what direction. Walk me through this more)
3) Infrequent use, discovering any bus stops and schedules near by (Show me everything, give me suggestions)

Also, I would want a different display, with the ability to see either expandable bus routes or a long list buses departing sorted ascending on departure for major hubs.

**Comment by itsjustluck** [comment]
Sorry that it too so long. Hopefully things will go faster now that I have some assets.

@kanishka-azimi Thank you for your feedback. Do the mockups below address your need for a clearer arrival time?

![instabus-stoptimes-v1](https://cloud.githubusercontent.com/assets/2096627/9984390/2fb84a46-5fdc-11e5-8129-a78088b7bba5.png)
![instabus-stoptimes-v2](https://cloud.githubusercontent.com/assets/2096627/9984398/50c3785a-5fdc-11e5-8382-c2431ff12ece.png)

**Comment by luqmaan** [comment]
What does the clock icon do?
![image](https://cloud.githubusercontent.com/assets/1275831/9984701/5aa9db9c-5fe2-11e5-98b8-bc1158075c83.png)

Is that the right place for the back button? In terms of the Google UI, isn't that usually where you put the primary "action" button? E.g. in Inbox it is the "Compose Email" button.

**Comment by itsjustluck** [comment]
The clock icon is an indicator that this is the time selected for the timer feature. Perhaps "Next Bus" should change to "Selected Bus" for the title. The not activated clocks would probably make more sense if they were a disabled (gray) color.

Personally, I like the idea of being able to quickly glance at the app and make sure that I'm looking at the time when I'm trying to decide when I need to leave for the bus stop. I've missed lot of buses due to bad time keeping.  ¯\_(ツ)_/¯

Right on that back button. I wanted to find a map icon, but I couldn't find one I liked. I can try another example with a proper back button in the upper left corner.

I like the context of being in the map (especially being able to explore nearby stops while still in times context), but I can try a version without it.
